channels:
- conda-forge
dependencies:
- python=3.9.13
- pip<=24.3.1
- pip:
  - mlflow==2.19.0
  - argparse==1.4.0
  - cloudpickle==2.2.1
  - numpy==1.24.1
  - pandas==1.5.2
  - psutil==5.9.4
  - scikit-learn==1.2.1
  - scipy==1.10.1
  - xgboost==1.6.1
name: mlflow-env
